### ISSUE TITLE
Call to undefined method Chess\WebBundle\Translation\Translator::transChoice()

### ISSUE THREAD

**Issue by umpirsky** [Limenius/Liform#66]
Happens in Symfony5:

```
Error: Call to undefined method Chess\WebBundle\Translation\Translator::transChoice()
#10 /vendor/limenius/liform/src/Limenius/Liform/Serializer/Normalizer/FormErrorNormalizer.php(99): Limenius\Liform\Serializer\Normalizer\FormErrorNormalizer::getErrorMessage
#9 /vendor/limenius/liform/src/Limenius/Liform/Serializer/Normalizer/FormErrorNormalizer.php(70): Limenius\Liform\Serializer\Normalizer\FormErrorNormalizer::convertFormToArray
#8 /vendor/limenius/liform/src/Limenius/Liform/Serializer/Normalizer/FormErrorNormalizer.php(47): Limenius\Liform\Serializer\Normalizer\FormErrorNormalizer::normalize
```

https://github.com/symfony/symfony-docs/issues/11002

**Comment by nacmartin** [comment]
Should be working now after merthing the related PRs
